import { auth, db } from './firebase-config.js';
import { collection,getDocs,query,where,doc,writeBatch,deleteDoc } from 'https://www.gstatic.com/firebasejs/12.19.0/firebase-firestore.js';
const C='outings',$=id=>document.getElementById(id),pad=n=>String(n).padStart(2,'0');let rows=[];
function txt(v){return String(v??'').trim()} function norm(v){return txt(v).replace(/\s+/g,'')} function esc(v){return txt(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function dateVal(v){if(v instanceof Date&&!isNaN(v))return `${v.getFullYear()}-${pad(v.getMonth()+1)}-${pad(v.getDate())}`;if(typeof v==='number'){const d=XLSX.SSF.parse_date_code(v);if(d)return `${d.y}-${pad(d.m)}-${pad(d.d)}`}const m=txt(v).match(/(20\d{2})[.\/-](\d{1,2})[.\/-](\d{1,2})/);return m?`${m[1]}-${pad(m[2])}-${pad(m[3])}`:''}
function timeVal(v){if(v instanceof Date)return `${pad(v.getHours())}:${pad(v.getMinutes())}`;if(typeof v==='number'&&v>=0&&v<1){const n=Math.round(v*1440)%1440;return `${pad(Math.floor(n/60))}:${pad(n%60)}`}const m=txt(v).match(/(\d{1,2})\s*[:시]\s*(\d{1,2})/);return m?`${pad(m[1])}:${pad(m[2])}`:''}
function mins(a,b){const x=a.split(':').map(Number),y=b.split(':').map(Number);if(x.length<2||y.length<2)return 0;let d=y[0]*60+y[1]-(x[0]*60+x[1]);if(d<0)d+=1440;return d}
function isStaff(comp){return /직원\s*동행/.test(txt(comp))}
function parseWB(wb,fileName){const out=[];wb.SheetNames.forEach(sn=>{const a=XLSX.utils.sheet_to_json(wb.Sheets[sn],{header:1,defval:'',raw:true});let h=-1;for(let i=0;i<a.length;i++){const s=(a[i]||[]).map(norm);if(s.includes('외출일')&&s.includes('외출시간')&&s.includes('수급자명')){h=i;break}}if(h<0)return;const hd=a[h].map(norm),idx=(...ks)=>hd.findIndex(x=>ks.some(k=>x.includes(norm(k))));const c={date:idx('외출일'),out:idx('외출시간'),back:idx('복귀시간'),use:idx('급여이용여부'),name:idx('수급자명'),purpose:idx('외출목적'),dest:idx('행선지'),comp:idx('동행보호자','동행 보호자'),writer:idx('작성자'),hospital:idx('병원'),memo:idx('비고')};let carry='';for(let r=h+1;r<a.length;r++){const x=a[r]||[];const d=dateVal(x[c.date]);if(d)carry=d;const name=txt(x[c.name]);if(!carry||!name)continue;const o=timeVal(x[c.out]),b=timeVal(x[c.back]),comp=txt(x[c.comp]),staff=isStaff(comp),duration=mins(o,b);out.push({date:carry,month:carry.slice(0,7),recipientName:name,outTime:o,returnTime:b,durationMinutes:duration,benefitUse:txt(x[c.use]),purpose:txt(x[c.purpose]),destination:txt(x[c.dest]),companion:comp,writer:txt(x[c.writer]),hospital:txt(x[c.hospital]),memo:txt(x[c.memo]),staffAccompanied:staff,deductible:!staff&&duration>0,fileName,sheetName:sn});}});return out}
function idFor(x){return `${x.date}_${x.recipientName}_${x.outTime}_${x.returnTime}`.replace(/[^0-9A-Za-z가-힣_-]/g,'_')}
async function upload(){const fs=[...$('outingFile').files];if(!fs.length)return alert('외출 목록 엑셀을 선택해주세요.');if(!auth.currentUser)return alert('로그인이 필요합니다.');let all=[];for(const f of fs){const wb=XLSX.read(await f.arrayBuffer(),{type:'array',cellDates:true});all.push(...parseWB(wb,f.name))}if(!all.length)return alert('외출 기록을 찾지 못했습니다.');$('status').textContent=`${all.length}건 저장 중...`;for(let i=0;i<all.length;i+=400){const b=writeBatch(db);all.slice(i,i+400).forEach(x=>b.set(doc(db,C,idFor(x)),{...x,ownerUid:auth.currentUser.uid,uploadedAt:new Date().toISOString(),uploadedBy:auth.currentUser.email||''},{merge:true}));await b.commit()}$('status').textContent=`외출 ${all.length}건 저장 완료`;if(all[0]?.month)$('month').value=all[0].month;await load()}
async function load(){const m=$('month').value;if(!m)return alert('조회 월을 선택해주세요.');$('status').textContent='불러오는 중...';const snap=await getDocs(query(collection(db,C),where('month','==',m)));rows=snap.docs.map(d=>({...d.data(),firestoreId:d.id,checked:false})).sort((a,b)=>(a.date+a.outTime).localeCompare(b.date+b.outTime));$('status').textContent=`${m} 외출 ${rows.length}건`;render()}
function render(){$('total').textContent=rows.length;$('staff').textContent=rows.filter(x=>x.staffAccompanied).length;$('deduct').textContent=rows.filter(x=>x.deductible).length;$('body').innerHTML=rows.length?rows.map((x,i)=>`<tr><td><input class="pick" data-i="${i}" type="checkbox"></td><td>${x.date}</td><td><b>${esc(x.recipientName)}</b></td><td>${esc(x.outTime)}</td><td>${esc(x.returnTime)}</td><td>${x.durationMinutes||0}분</td><td>${esc(x.benefitUse)}</td><td>${esc(x.purpose)}</td><td>${esc(x.destination)}</td><td>${esc(x.companion)}</td><td class="${x.staffAccompanied?'staff':''}">${x.staffAccompanied?'직원동행':'아님'}</td><td class="${x.deductible?'deduct':''}">${x.deductible?`${x.durationMinutes}분 차감`:'차감 없음'}</td><td>${esc(x.writer)}</td><td>${esc(x.memo)}</td></tr>`).join(''):'<tr><td colspan="14" class="empty">해당 월 외출 기록이 없습니다.</td></tr>';document.querySelectorAll('.pick').forEach(e=>e.onchange=()=>rows[+e.dataset.i].checked=e.checked)}
async function del(){const sel=rows.filter(x=>x.checked);if(!sel.length)return alert('삭제할 외출 기록을 선택해주세요.');if(!confirm(`${sel.length}건을 삭제할까요?`))return;await Promise.all(sel.map(x=>deleteDoc(doc(db,C,x.firestoreId))));await load()}
function exp(){if(!rows.length)return alert('다운로드할 자료가 없습니다.');const data=rows.map(x=>({'외출일':x.date,'수급자명':x.recipientName,'외출시간':x.outTime,'복귀시간':x.returnTime,'외출시간(분)':x.durationMinutes,'급여이용여부':x.benefitUse,'외출목적':x.purpose,'행선지':x.destination,'동행 보호자':x.companion,'직원동행':x.staffAccompanied?'예':'아니오','수가 차감':x.deductible?`${x.durationMinutes}분`:'없음','작성자':x.writer,'비고':x.memo}));const ws=XLSX.utils.json_to_sheet(data),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'외출');XLSX.writeFile(wb,`외출_보관함_${$('month').value}.xlsx`)}
$('uploadBtn').onclick=upload;$('loadBtn').onclick=load;$('deleteBtn').onclick=del;$('exportBtn').onclick=exp;$('all').onchange=e=>{rows.forEach(x=>x.checked=e.target.checked);document.querySelectorAll('.pick').forEach(x=>x.checked=e.target.checked)};$('month').value=new Date().toISOString().slice(0,7);
