(function(){
const periods=[['23년 마지막분기','2023-10-01','2023-12-31'],['24년 상반기','2024-01-01','2024-04-30'],['24년 중간기','2024-05-01','2024-08-31'],['24년 하반기','2024-09-01','2024-12-31'],['25년 상반기','2025-01-01','2025-04-30'],['25년 중간기','2025-05-01','2025-08-31'],['25년 하반기','2025-09-01','2025-12-31'],['26년 상반기','2026-01-01','2026-06-30'],['26년 하반기','2026-07-01','2026-12-31']];
let current=[]; const $=id=>document.getElementById(id); const txt=v=>String(v??'').trim();
function date(v){let s=txt(v).replace(/[.\/]/g,'-');let m=s.match(/(20\d{2})-(\d{1,2})-(\d{1,2})/);return m?`${m[1]}-${m[2].padStart(2,'0')}-${m[3].padStart(2,'0')}`:''}
function count(v){let m=txt(v).match(/주\s*(\d+)\s*회?/);return m?`주${m[1]}`:''}
function hour(v){let s=txt(v).replace(/\s/g,''); if(/3시간미만/.test(s))return'3미만'; let m=s.match(/(\d+)시간이상(\d+)시간미만/); if(m)return m[1]; if(/13시간(이상|초과)/.test(s))return'13+'; return''}
function pair(c,f){const a=count(c),b=hour(f);return a&&b?`${a}*${b}`:''}
function code(p){const wd=pair(p.weekdayWeeklyCount,p.weekdayFee),we=pair(p.weekendWeeklyCount,p.weekendFee),pl=pair(p.planWeeklyCount,p.planFee);return [wd,we].filter(Boolean).join(' / ')||pl||'-'}
function overlap(p,a,b){const s=date(p.applicationStartDate||p.writtenDate)||'1900-01-01',e=date(p.applicationEndDate)||'2999-12-31';return s<=b&&e>=a}
function esc(s){return txt(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function render(plans){const map=new Map();plans.forEach(p=>{const name=txt(p.recipientName||p.name);if(!name||name==='성명')return;const key=txt(p.longTermNumber)||name;if(!map.has(key))map.set(key,{name,plans:[]});map.get(key).plans.push(p)});current=[...map.values()].sort((a,b)=>a.name.localeCompare(b.name,'ko'));$('feeHistoryBody').innerHTML=current.map(x=>`<tr><td>${esc(x.name)}</td>${periods.map(([_,a,b])=>{const ps=x.plans.filter(p=>overlap(p,a,b)).sort((u,v)=>date(u.applicationStartDate||u.writtenDate).localeCompare(date(v.applicationStartDate||v.writtenDate)));const vals=[];ps.forEach(p=>{const c=code(p),d=date(p.applicationStartDate||p.writtenDate);const val=ps.length>1?`${c}${d?` (${d.slice(5)}~)`:''}`:c;if(!vals.includes(val))vals.push(val)});return `<td>${esc(vals.join('\n')||'-')}</td>`}).join('')}</tr>`).join('')||'<tr><td colspan="10" class="empty">계획서 데이터가 없습니다.</td></tr>';$('feeStatus').textContent=`${current.length}명 · 계획서 ${plans.length}건`}
async function load(){try{$('feeStatus').textContent='Firebase에서 불러오는 중...';while(!window.HanmaumFirestore)await new Promise(r=>setTimeout(r,50));render(await window.HanmaumFirestore.allCarePlans())}catch(e){console.error(e);$('feeStatus').textContent='불러오기 실패';alert('수가표를 불러오지 못했습니다: '+e.message)}}
function download(){if(!current.length){alert('먼저 수가표를 불러와주세요.');return}const rows=[['수급자명',...periods.map(p=>p[0])],...current.map(x=>[x.name,...periods.map(([_,a,b])=>{const ps=x.plans.filter(p=>overlap(p,a,b)).sort((u,v)=>date(u.applicationStartDate||u.writtenDate).localeCompare(date(v.applicationStartDate||v.writtenDate)));return ps.map(p=>code(p)).filter((v,i,a)=>a.indexOf(v)===i).join('\n')||'-'})])];const ws=XLSX.utils.aoa_to_sheet(rows);ws['!cols']=[{wch:14},...periods.map(()=>({wch:24}))];const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'수가변동표');XLSX.writeFile(wb,`수가변동표_${new Date().toISOString().slice(0,10)}.xlsx`)}
document.addEventListener('DOMContentLoaded',()=>{$('reloadFee').onclick=load;$('downloadFee').onclick=download;load()});
})();
